name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/initialize
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ghcr.io/himenon/texlive-ja:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
